### ISSUE TITLE
Test RaspberryPi compatibility

### ISSUE THREAD

**Issue by extrapixel** [whitebox-labs/tentacle#1]
via connection bridge etc. If compatible, make wiring and coding examples.

**Comment by ShaneKirkbride** [comment]
I tested this configuration. It is compatible with the 2 port board at least.

**Comment by extrapixel** [comment]
Confirmed compatible with a level-shifter. However, consider using the new Tentacle T3 for Raspberry Pi for simpler connection to the Pi.
