### ISSUE TITLE
rename watersens to tentacle in files, references etc

### ISSUE THREAD

**Issue by extrapixel** [whitebox-labs/tentacle#4]

**Comment by steve-worrall** [comment]
-look into changing project file names.
--difficult to do, as modules in PBC new refer to libuary file names when importing one time only, by changing the name we lose the projects associations to the schematic, without deleting all the components from the design, reimporting the net list, it's like editing the files names in a compiled program. It can be done, but you'd have to replace every reference to those file names in the code.

**Comment by extrapixel** [comment]
we'll keep this open.

**Comment by extrapixel** [comment]
we'll do the same as in whitebox-labs/tentacle-raspi#1
